apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hub_v1alpha1_deploymentdescriptor.yaml
- sample-rs-dispatcher-d2-msu.yaml
- sample-rs-dispatcher-d2-ssu.yaml
- sample-rs-dispatcher-d2-vsu.yaml
- sample-rs-dispatcher-d4-msu.yaml
- sample-rs-dispatcher-d4-vsu.yaml
- sample-rs-dispatcher-t2-msu.yaml
- sample-rs-dispatcher-t2-vsu.yaml
- sample-rs-srm-d2-ssu.yaml
- sample-rs-srm-d4-ssu.yaml
- sample-rs-srm-t2-ssu.yaml
